# Generated by Django 5.0.14 on 2025-10-21 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="ID of the tenant this role belongs to"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., 'Manager', 'Receptionist', 'Therapist')",
                        max_length=100,
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                            ("viewer", "Viewer"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        help_text="Type of role - system roles are protected from modification",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this role can do"),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="Array of Django permission codenames this role grants",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="System roles cannot be deleted or have their type changed",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive roles cannot be assigned to users",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional role configuration (e.g., UI permissions, feature flags)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant Role",
                "verbose_name_plural": "Tenant Roles",
                "db_table": "rbac_tenant_role",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active"], name="rbac_tenant_tenant__d8a531_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "role_type"], name="rbac_tenant_tenant__5b1c64_idx"
                    ),
                    models.Index(fields=["is_system"], name="rbac_tenant_is_syst_09128b_idx"),
                ],
                "unique_together": {("tenant_id", "name")},
            },
        ),
    ]
