# Generated by Django 5.0.14 on 2025-10-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tenantmembership",
            name="unique_tenant_user",
        ),
        migrations.RenameIndex(
            model_name="tenantmembership",
            new_name="users_tenan_tenant__ece498_idx",
            old_name="tenant_user_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmembership",
            new_name="users_tenan_tenant__06adf8_idx",
            old_name="tenant_active_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmembership",
            new_name="users_tenan_role_72e3f8_idx",
            old_name="role_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_email_6f2530_idx",
            old_name="users_user_email_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_is_acti_ddda02_idx",
            old_name="users_user_is_active_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("tenant_id", "user")},
        ),
    ]
