# Generated by Django 5.0.14 on 2025-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_tenantmembership_unique_tenant_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmembership",
            name="rbac_role_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID of the TenantRole in the tenant's schema (preferred over legacy 'role' field)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="permissions",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom permission overrides (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                help_text="Deprecated: Use rbac_role_id instead",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(fields=["rbac_role_id"], name="users_tenan_rbac_ro_8f1aa2_idx"),
        ),
    ]
