# Generated by Django 5.0.14 on 2025-10-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_tenantmembership_rbac_role_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tenantmembership",
            name="users_tenan_role_72e3f8_idx",
        ),
        migrations.RemoveField(
            model_name="tenantmembership",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="tenantmembership",
            name="role",
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="rbac_role_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID of the TenantRole in the tenant's schema",
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
