# Generated by Django 5.0.14 on 2025-10-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_tenant_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_tenant__79c011_idx",
            old_name="users_user_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_tenant__b409af_idx",
            old_name="users_user_tenant__active_idx",
        ),
    ]
