# Generated by Django 5.0.14 on 2025-10-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_users_user_tenant__idx_users_user_tenant__79c011_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tenantmembership",
            name="users_tenan_rbac_ro_8f1aa2_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_tenant__79c011_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_tenant__b409af_idx",
        ),
        migrations.RemoveField(
            model_name="tenantmembership",
            name="rbac_role_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tenant_id",
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(fields=["role"], name="users_tenan_role_72e3f8_idx"),
        ),
    ]
