# Generated by Django 5.0.14 on 2025-10-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
        ("users", "0007_remove_tenantmembership_users_tenan_rbac_ro_8f1aa2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmembership",
            name="tenant_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role assigned to this user in the tenant",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="rbac.tenantrole",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="DEPRECATED: Use tenant_role.permissions instead",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(fields=["tenant_role"], name="users_tenan_tenant__810de0_idx"),
        ),
    ]
