# Generated by Django 5.0.14 on 2025-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_alter_tenantlifecycle_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("salon", "Salon / Barbershop"),
                    ("clinic", "Medical Clinic"),
                    ("gym", "Gym / Fitness Center"),
                    ("spa", "Spa / Wellness Center"),
                    ("studio", "Studio (Yoga, Dance, Art)"),
                    ("restaurant", "Restaurant"),
                    ("custom", "Custom / Other"),
                ],
                db_index=True,
                default="custom",
                help_text="Type of business - determines which modules are enabled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="enabled_modules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Granular control over enabled modules from base_start (e.g., {'bookings': True, 'payments': False})",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["app_type"], name="tenant_tena_app_typ_f3622a_idx"),
        ),
    ]
