# Generated by Django 5.0.14 on 2025-10-21 19:35

import uuid
from django.db import migrations, models


def set_tenant_uuids(apps, schema_editor):
    """
    Add UUID column and populate it with converted integer IDs.
    Format: 00000000-0000-0000-0000-{hex_id:012x}
    Example: 14 -> 00000000-0000-0000-0000-00000000000e
    """
    db_alias = schema_editor.connection.alias

    # Use raw SQL to update the new_id column
    with schema_editor.connection.cursor() as cursor:
        # Get all tenants
        cursor.execute("SELECT id, name FROM public.tenant_tenant")
        tenants = cursor.fetchall()

        for tenant_id, tenant_name in tenants:
            # Convert integer to UUID format
            new_uuid = f'00000000-0000-0000-0000-{tenant_id:012x}'
            cursor.execute(
                "UPDATE public.tenant_tenant SET new_id = %s WHERE id = %s",
                [new_uuid, tenant_id]
            )
            print(f"Tenant '{tenant_name}': {tenant_id} -> {new_uuid}")


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_tenant_app_type_tenant_enabled_modules_and_more"),
    ]

    operations = [
        # Step 1: Add new UUID column (not primary key yet)
        migrations.AddField(
            model_name="tenant",
            name="new_id",
            field=models.UUIDField(null=True, editable=False),
        ),

        # Step 2: Populate new_id with converted values
        migrations.RunPython(set_tenant_uuids, migrations.RunPython.noop),

        # Step 3: Make new_id non-nullable
        migrations.AlterField(
            model_name="tenant",
            name="new_id",
            field=models.UUIDField(editable=False),
        ),

        # Step 4: Remove old id and rename new_id to id
        migrations.RemoveField(
            model_name="tenant",
            name="id",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="new_id",
            new_name="id",
        ),

        # Step 5: Make id the primary key
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
