# Generated by Django 5.2.7 on 2025-10-18 08:34

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text='Business/Company name', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], db_index=True, default='trial', max_length=20)),
                ('primary_domain', models.CharField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('subscription_tier', models.CharField(default='free', max_length=50)),
                ('max_staff', models.PositiveIntegerField(default=5)),
                ('max_services', models.PositiveIntegerField(default=10)),
                ('max_bookings_per_month', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_tenant',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tenant_tena_status_61b171_idx'), models.Index(fields=['subscription_tier'], name='tenant_tena_subscri_33d5b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.tenant')),
            ],
            options={
                'db_table': 'tenant_domain',
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('locale', 'Localization'), ('features', 'Features'), ('limits', 'Limits'), ('integrations', 'Integrations'), ('notifications', 'Notifications'), ('payments', 'Payments'), ('custom', 'Custom')], db_index=True, default='custom', max_length=50)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='tenant.tenant')),
            ],
            options={
                'db_table': 'tenant_config',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['tenant', 'category'], name='tenant_conf_tenant__b679c1_idx'), models.Index(fields=['key'], name='tenant_conf_key_f823c5_idx')],
                'unique_together': {('tenant', 'category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TenantLifecycle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], db_index=True, max_length=50)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='tenant.tenant')),
            ],
            options={
                'db_table': 'tenant_lifecycle',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'event'], name='tenant_life_tenant__46f9b9_idx'), models.Index(fields=['occurred_at'], name='tenant_life_occurre_59adc4_idx')],
            },
        ),
    ]
